server:
  port: 8081

spring:
  application:
    name: product-demo
  datasource:
    url: jdbc:postgresql://localhost:5432/products_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate


logging:
  level:
    org.springframework.transaction=TRACE: TRACE
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE